[package]
name = "pcie_mem_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
memmap2 = "0.5"
tempfile = "3"

[profile.test]
opt-level = 3
